[workspace]
members = [
  "programs/factory",
  "programs/vault",
  "programs/pool",
  "programs/verifier-groth16"
]

[programs.localnet]
ptf_factory = "4z618BY2dXGqAUiegqDt8omo3e81TSdXRHt64ikX1bTy"
ptf_vault = "9g6ZodQwxK8MN6MX3dbvFC3E7vGVqFtKZEHY7PByRAuh"
ptf_pool = "7kbUWzeTPY6qb1mFJC1ZMRmTZAdaHC27yukc3Czj7fKh"
ptf_verifier_groth16 = "3aCv39mCRFH9BGJskfXqwQoWzW1ULq2yXEbEwGgKtLgg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

